# Generated by Django 5.2.13 on 2026-04-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
